# Local.
#path_to_dataset: '/home/andrea/dev/uni/datasets/serialized_dataset'
#aim_logs_path: '../aim'
#model_checkpoint_path: '../models'
#model_config_csv_log_path: '../model_settings.csv'

# Docker paths.
#dataset_path: '/mnt/datasets/serialized_dataset'
#logs_path: '/mnt/logs'
#aim_logs_path: '/mnt/aim'
#model_checkpoint_path: '/mnt/model-checkpoints'
#model_histories: '/mnt/model_histories'
#model_config_csv_log_path: '/mnt/model_settings.csv'
#model_evaluation_csv_log_path: '/mnt/model_evaluation.csv'

# Personal laptop paths.
dataset_path: '/Users/andreaspiteri/uni/datasets/serialized_dataset'
logs_path: '/Users/andreaspiteri/uni/auditory-deepdream/logs'
aim_logs_path: '/Users/andreaspiteri/uni/auditory-deepdream/logs/aim'
model_checkpoint_path: '/Users/andreaspiteri/uni/auditory-deepdream/models'
model_histories: '/Users/andreaspiteri/uni/auditory-deepdream/logs/model_histories'
model_config_csv_log_path: '/Users/andreaspiteri/uni/auditory-deepdream/logs/model_settings.csv'
model_evaluation_csv_log_path: '/Users/andreaspiteri/uni/auditory-deepdream/logs/model_evaluation.csv'
