version: '3.7'

services:
  jupyter:
    image: aspit002/audio-deepdream-dev-env
    volumes:
      - ./jupyter-notebooks:/notebook
      - ./data-sets:/data-sets
      - ./audio-files:/audio-files
      - ./images:/images
      - ./pickled-data:/pickled-data
      - ./tensorboard-logs:/tensorboard-logs
      - ./models:/models

      # Mounting my library directory to the PYTHONPATH in the docker container.
      - ./lib/deep_dream:/usr/local/lib/python3.8/dist-packages/deep_dream
      - ./lib/utils:/usr/local/lib/python3.8/dist-packages/utils
    command: jupyter notebook /notebook --port=8888 --ip=0.0.0.0 --allow-root
    ports:
      - "8888:8888"
      - "6006:6006"
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 4gb
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1s
#              capabilities: [ compute, utility ]

  tensorboard:
    image: lspvic/tensorboard-notebook
    volumes:
      - ./tensorboard-logs:/tensorboard-logs
    command: tensorboard --logdir='/tensorboard-logs' --port 8020 --host=0.0.0.0
    ports:
      - "8020:8020"