version: '3.7'

services:
  jupyter:
    image: aspit002/audio-deepdream-dev-env
    volumes:
      - ./jupyter-notebooks:/notebook
      - ./data-sets:/data-sets
      - ./pickled-data:/pickled-data
      - ./tensorboard-logs:/tensorboard-logs
      - ./models:/models
    command: jupyter notebook /notebook --port=8888 --ip=0.0.0.0 --allow-root
    ports:
      - "8888:8888"
      - "6006:6006"
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 4gb
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ compute, utility ]

  tensorboard:
    image: lspvic/tensorboard-notebook
    volumes:
      - ./tensorboard-logs:/tensorboard-logs
    command: tensorboard --logdir='/tensorboard-logs' --port 8020 --host=0.0.0.0
    ports:
      - "8020:8020"