version: '3.7'

services:
  # Service for starting up a jupyter server.
  jupyter:
    image: aspit002/audio-deepdream-dev-env-jupyter
    volumes:
      - ../datasets:/mnt/datasets
      - ./models:/mnt/models
      - ./logs:/mnt/logs
      - ./logs/aim:/mnt/aim
      - ./logs/feature_visualization:/mnt/feature_visualization

      # Mounting my library directory to the PYTHONPATH in the docker container.
      - ./library/deep_dream:/usr/local/lib/python3.8/dist-packages/deep_dream
      - ./library/utils:/usr/local/lib/python3.8/dist-packages/utils
      - ./library/ai_tools:/usr/local/lib/python3.8/dist-packages/ai_tools
      - ./long-audio:/mnt/long-audio
    ports:
      - "8888:8888"
      - "6006:6006"
    deploy:
      resources:
        limits:
          cpus: 6
          memory: 20gb
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ compute, utility ]

  # Service which will run ./src/main.py.
  script-runner:
    image: aspit002/audio-deepdream-dev-env
    volumes:
      - ../datasets:/mnt/datasets
      - ./models:/mnt/models
      - ./logs:/mnt/logs
      - ./long-audio:/mnt/long-audio
      - ./media:/mnt/media
      - ./runs:/mnt/runs
      - ./layer_outputs:/mnt/layer_outputs
      - ./feature_visualization:/mnt/feature_visualization

      # Mounting my library directory to the PYTHONPATH in the docker container.
      - ./library/deep_dream:/usr/local/lib/python3.8/dist-packages/deep_dream
      - ./library/utils:/usr/local/lib/python3.8/dist-packages/utils
      - ./library/ai_tools:/usr/local/lib/python3.8/dist-packages/ai_tools
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 20gb
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ compute, utility ]

  aim:
    image: aspit002/aim-logs
    volumes:
      - ./logs/aim:/aim
#      - ./runs/run_1/aim:/aim
#      - ./runs/run_2/aim:/aim
#      - ./runs/run_3/aim:/aim
    ports:
      - "43800:43800"
