# Extends an existing docker container by installing some additional dependencies specific for audio AI.
# Source: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/dockerfiles/dockerfiles/gpu-jupyter.Dockerfile
FROM tensorflow/tensorflow:latest-gpu-jupyter

# Python
RUN pip install librosa opencv-python scikit-image pydub kapre sox soundfile numpy==1.19.2 tqdm seaborn pandas aim pyyaml

RUN apt-get update
RUN apt-get install -y sox libsox-fmt-mp3 ffmpeg libsm6 libxext6